#server.port=8080

logging:
  level:
    org.springframework.web: ERROR
    com.ericsson.eiffel.remrem.producer: ERROR

# need to be updated according to the test env.
#rabbitmq.host=mb101-eiffel010.lmera.ericsson.se
# must exist
#rabbitmq.exchange.name=eiffel.poc

rabbitmq:
  host: 127.0.0.1
  port:
  user:
  password:
  tls:
  #host: mb101-eiffel010.lmera.ericsson.se
  exchange:
    name: amq.direct
  domainId: eiffelxxx
spring:
  http.converters:
    preferred-json-mapper: gson

activedirectory:
  enabled: false
  domain:
  url:

